import { useEffect, useMemo, useState, type FormEvent } from 'react';
import { Check, CircleCheck, CreditCard, Eye, MapPin, Minus, Plus, Search, ShoppingBag, SlidersHorizontal, Trash2, Truck, X } from 'lucide-react';
import { AnimatePresence, motion } from 'motion/react';

type Product = { id:string; name:string; category:string; unit:string; description:string; image:string; badge?:string; specs:string[]; uses:string };
type Cart = Record<string, number>;
type Sort = 'featured'|'name'|'category';

const products: Product[] = [
  {id:'angle-grinder',name:'Angle Grinder 115mm',category:'Power tools',unit:'each',description:'Compact grinder for cutting, grinding and surface preparation.',uses:'Metal cutting, masonry and surface preparation',specs:['115mm disc format','Side-handle compatible','Corded power tool'],badge:'Trade essential',image:'https://images.unsplash.com/photo-1504148455328-c376907d081c?auto=format&fit=crop&w=900&q=82'},
  {id:'cordless-drill',name:'Cordless Drill Set',category:'Power tools',unit:'set',description:'Versatile drill-driver kit for installation and site work.',uses:'Drilling, fastening and general installation',specs:['Cordless format','Variable-speed control','Supplied as a set'],image:'https://images.unsplash.com/photo-1572981779307-38b8cabb2407?auto=format&fit=crop&w=900&q=82'},
  {id:'claw-hammer',name:'Claw Hammer',category:'Hand tools',unit:'each',description:'Balanced general-purpose hammer with a durable grip.',uses:'Framing, fixing and nail removal',specs:['Claw-head profile','Textured grip','General site use'],image:'https://images.unsplash.com/photo-1586864387789-628af9feed72?auto=format&fit=crop&w=900&q=82'},
  {id:'spanner-set',name:'Combination Spanner Set',category:'Hand tools',unit:'set',description:'Metric spanner selection for workshop and maintenance use.',uses:'Mechanical fitting, repair and maintenance',specs:['Metric selection','Open and ring ends','Storage set'],image:'https://images.unsplash.com/photo-1530124566582-a618bc2615dc?auto=format&fit=crop&w=900&q=82'},
  {id:'padlock',name:'Heavy-Duty Padlock',category:'Security',unit:'each',description:'Hardened lock for gates, stores and tool boxes.',uses:'Securing gates, stores and equipment',specs:['Hardened shackle','Key-operated','Outdoor utility'],image:'https://images.unsplash.com/photo-1558002038-1055907df827?auto=format&fit=crop&w=900&q=82'},
  {id:'safety-kit',name:'Site Safety Kit',category:'Safety',unit:'kit',description:'Core personal protective equipment for everyday site work.',uses:'General construction and maintenance sites',specs:['Multi-item kit','High-visibility components','General site protection'],badge:'Site ready',image:'https://images.unsplash.com/photo-1578874691223-64558a3ca096?auto=format&fit=crop&w=900&q=82'},
  {id:'pvc-pipe',name:'PVC Pressure Pipe',category:'Plumbing',unit:'length',description:'General water and plumbing pipe in selectable specifications.',uses:'Water supply and general plumbing runs',specs:['PVC construction','Multiple diameters available','Specification confirmed on quote'],image:'https://images.unsplash.com/photo-1581094794329-c8112a89af12?auto=format&fit=crop&w=900&q=82'},
  {id:'paint-roller',name:'Paint Roller Kit',category:'Paint & finish',unit:'kit',description:'Roller, tray and accessories for walls and ceilings.',uses:'Interior and exterior paint application',specs:['Roller and tray','Replaceable sleeve format','Wall and ceiling use'],image:'https://images.unsplash.com/photo-1562259929-b4e1fd3aef09?auto=format&fit=crop&w=900&q=82'},
];
const categories=['All',...Array.from(new Set(products.map(p=>p.category)))];

export function HardwareShop(){
  const [category,setCategory]=useState('All'); const [query,setQuery]=useState(''); const [sort,setSort]=useState<Sort>('featured');
  const [cart,setCart]=useState<Cart>(()=>{try{return JSON.parse(localStorage.getItem('tash-quote-cart')||'{}') as Cart}catch{return {}}});
  const [cartOpen,setCartOpen]=useState(false); const [selected,setSelected]=useState<Product|null>(null); const [checkoutOpen,setCheckoutOpen]=useState(false);
  const [lastAdded,setLastAdded]=useState<string|null>(null); const [orderNumber,setOrderNumber]=useState<string|null>(null);
  useEffect(()=>localStorage.setItem('tash-quote-cart',JSON.stringify(cart)),[cart]);
  useEffect(()=>{document.body.style.overflow=(cartOpen||selected||checkoutOpen)?'hidden':'';return()=>{document.body.style.overflow=''}},[cartOpen,selected,checkoutOpen]);
  const filtered=useMemo(()=>products.filter(p=>(category==='All'||p.category===category)&&`${p.name} ${p.description} ${p.uses}`.toLowerCase().includes(query.toLowerCase())).sort((a,b)=>sort==='name'?a.name.localeCompare(b.name):sort==='category'?a.category.localeCompare(b.category):0),[category,query,sort]);
  const quantity=(id:string)=>Number(cart[id]||0); const count=Object.keys(cart).reduce((total,id)=>total+quantity(id),0);
  const change=(id:string,amount:number)=>{
    setCart(current=>{const next:Cart={...current};next[id]=Math.max(0,Number(next[id]||0)+amount);if(!next[id])delete next[id];return next});
    if(amount>0){const product=products.find(p=>p.id===id);setLastAdded(product?.name||'Product');window.setTimeout(()=>setLastAdded(null),2600)}
  };
  const cartProducts=products.filter(p=>quantity(p.id)>0);
  const placeOrder=(event:FormEvent<HTMLFormElement>)=>{event.preventDefault();const details=new FormData(event.currentTarget);const order=`OH-${Date.now().toString().slice(-6)}`;const list=cartProducts.map(p=>`• ${p.name} — ${quantity(p.id)} ${p.unit}${quantity(p.id)>1?'s':''}`).join('\n');const subject=encodeURIComponent(`Delivery order ${order}`);const body=encodeURIComponent(`ONLINE HARDWARE DELIVERY ORDER\nOrder: ${order}\n\nCUSTOMER\nName: ${details.get('name')}\nPhone: ${details.get('phone')}\nEmail: ${details.get('email')}\n\nDELIVERY\nAddress: ${details.get('address')}\nCity/area: ${details.get('area')}\nPreferred date: ${details.get('date')||'Next available'}\n\nPAYMENT\n${details.get('payment')}\n\nPRODUCTS\n${list}\n\nNotes: ${details.get('notes')||'None'}\n\nPlease confirm product prices, delivery fee and payment instructions before fulfilment.`);window.location.href=`mailto:tashhardware@gmail.com?subject=${subject}&body=${body}`;setOrderNumber(order);setCart({});setCartOpen(false)};
  const Qty=({product}: {product:Product})=>quantity(product.id)?<div className="qty"><button onClick={()=>change(product.id,-1)} aria-label={`Remove one ${product.name}`}><Minus/></button><span>{quantity(product.id)}</span><button onClick={()=>change(product.id,1)} aria-label={`Add one ${product.name}`}><Plus/></button></div>:<button className="add-product" onClick={()=>change(product.id,1)}><Plus/> Add to cart</button>;

  return <section className="shop section" id="shop">
    <div className="shop-head"><div><span className="kicker">ONLINE HARDWARE STORE</span><h2>Shop. Order.<br/>We deliver.</h2></div><div className="shop-intro"><p>Order tools and building essentials online for delivery across Zimbabwe. Choose your products, enter your address and receive a confirmed total before payment.</p><button className="cart-trigger" onClick={()=>setCartOpen(true)} aria-label={`Open quote basket with ${count} items`}><ShoppingBag/><span>Shopping cart</span><b>{count}</b></button></div></div>
    <div className="shop-tools"><label className="product-search"><Search/><span className="sr-only">Search products</span><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search tools, plumbing, safety…"/></label><div className="category-tabs" aria-label="Product categories">{categories.map(c=><button key={c} className={category===c?'active':''} onClick={()=>setCategory(c)}>{c}</button>)}</div></div>
    <div className="product-results"><span>{filtered.length} products</span><label className="sort-control"><SlidersHorizontal/><span>Sort</span><select value={sort} onChange={e=>setSort(e.target.value as Sort)}><option value="featured">Featured</option><option value="name">Name A–Z</option><option value="category">Category</option></select></label></div>
    <div className="product-grid">{filtered.map((p,i)=><motion.article className="product-card" key={p.id} initial={{opacity:0,y:18}} whileInView={{opacity:1,y:0}} viewport={{once:true}} transition={{delay:i*.035}}>
      <button className="product-image" onClick={()=>setSelected(p)} aria-label={`View details for ${p.name}`}>{p.badge&&<span>{p.badge}</span>}<img src={p.image} alt={p.name} width="900" height="700" loading="lazy" decoding="async"/><i><Eye/> Quick view</i></button>
      <div className="product-info"><small>{p.category}</small><button className="product-name" onClick={()=>setSelected(p)}><h3>{p.name}</h3></button><p>{p.description}</p><div className="product-buy"><div><b>Order online</b><span>per {p.unit}</span></div><Qty product={p}/></div></div>
    </motion.article>)}</div>
    {!filtered.length&&<div className="empty-products"><Search/><h3>No products found</h3><p>Try another search or category.</p><button onClick={()=>{setCategory('All');setQuery('')}}>Reset filters</button></div>}

    <AnimatePresence>{selected&&<><motion.button className="modal-backdrop" aria-label="Close product details" onClick={()=>setSelected(null)} initial={{opacity:0}} animate={{opacity:1}} exit={{opacity:0}}/><motion.div className="product-modal" role="dialog" aria-modal="true" aria-labelledby="product-dialog-title" initial={{opacity:0,y:28,scale:.98}} animate={{opacity:1,y:0,scale:1}} exit={{opacity:0,y:18,scale:.98}}><button className="modal-close" onClick={()=>setSelected(null)} aria-label="Close product details"><X/></button><div className="modal-image"><img src={selected.image} alt={selected.name}/></div><div className="modal-copy"><span className="kicker">{selected.category}</span><h3 id="product-dialog-title">{selected.name}</h3><p>{selected.description}</p><div className="product-specs"><h4>Product overview</h4><ul>{selected.specs.map(s=><li key={s}><Check/>{s}</li>)}</ul></div><div className="best-for"><small>BEST FOR</small><p>{selected.uses}</p></div><div className="modal-buy"><div><b>Order online</b><span>per {selected.unit}</span></div><Qty product={selected}/></div><button className="modal-basket" onClick={()=>{setSelected(null);setCartOpen(true)}}><ShoppingBag/> View quote basket ({count})</button></div></motion.div></>}</AnimatePresence>

    <AnimatePresence>{cartOpen&&<><motion.button className="cart-backdrop" aria-label="Close quote basket" onClick={()=>setCartOpen(false)} initial={{opacity:0}} animate={{opacity:1}} exit={{opacity:0}}/><motion.aside className="cart-drawer" aria-label="Shopping cart" initial={{x:'100%'}} animate={{x:0}} exit={{x:'100%'}} transition={{type:'spring',damping:28,stiffness:260}}><div className="cart-title"><div><span className="kicker">YOUR PRODUCT LIST</span><h3>Shopping cart <b>{count}</b></h3></div><button onClick={()=>setCartOpen(false)} aria-label="Close quote basket"><X/></button></div>
      {cartProducts.length?<><div className="cart-lines">{cartProducts.map(p=><div className="cart-line" key={p.id}><img src={p.image} alt=""/><div><small>{p.category}</small><h4>{p.name}</h4><span>{p.unit} · price confirmed before payment</span></div><div className="cart-line-actions"><Qty product={p}/><button className="remove" onClick={()=>setCart(c=>{const n={...c};delete n[p.id];return n})} aria-label={`Remove ${p.name}`}><Trash2/></button></div></div>)}</div><div className="cart-footer"><div><span>Products</span><b>{count}</b></div><div className="delivery-promise"><Truck/><span><b>Delivered to your address</b>Delivery timing and fee confirmed with your order.</span></div><button className="validate-quote" onClick={()=>{setCartOpen(false);setCheckoutOpen(true)}}><span>Continue to delivery</span><ShoppingBag/></button></div></>:<div className="empty-cart"><ShoppingBag/><h3>Your cart is empty</h3><p>Add hardware products to start a delivery order.</p><button onClick={()=>setCartOpen(false)}>Continue shopping</button></div>}
    </motion.aside></>}</AnimatePresence>
    <AnimatePresence>{checkoutOpen&&<><motion.button className="checkout-backdrop" aria-label="Close checkout" onClick={()=>setCheckoutOpen(false)} initial={{opacity:0}} animate={{opacity:1}} exit={{opacity:0}}/><motion.div className="checkout-modal" role="dialog" aria-modal="true" aria-labelledby="checkout-title" initial={{opacity:0,y:24}} animate={{opacity:1,y:0}} exit={{opacity:0,y:16}}><button className="checkout-close" onClick={()=>setCheckoutOpen(false)} aria-label="Close checkout"><X/></button>{orderNumber?<div className="order-confirmation"><CircleCheck/><span className="kicker">ORDER CREATED</span><h3 id="checkout-title">Thank you for your order.</h3><p>Your order reference is <b>{orderNumber}</b>. Your email app has opened with the complete order. Send it to Online Hardware so the team can confirm prices, delivery fee and payment instructions.</p><button onClick={()=>{setOrderNumber(null);setCheckoutOpen(false)}}>Continue shopping</button></div>:<><div className="checkout-heading"><span className="kicker">SECURE DELIVERY CHECKOUT</span><h3 id="checkout-title">Where should we deliver?</h3><div className="checkout-steps"><span className="active">1 Cart</span><span className="active">2 Delivery</span><span>3 Confirmation</span></div></div><form className="checkout-form" onSubmit={placeOrder}><label>Full name<input name="name" autoComplete="name" required/></label><label>Phone number<input name="phone" type="tel" autoComplete="tel" required/></label><label className="wide">Email address<input name="email" type="email" autoComplete="email" required/></label><label className="wide">Delivery address<input name="address" autoComplete="street-address" required placeholder="Street, stand or building"/></label><label>City / area<input name="area" required placeholder="e.g. Harare"/></label><label>Preferred delivery date<input name="date" type="date"/></label><fieldset className="wide"><legend>Payment preference</legend><label className="payment-option"><input type="radio" name="payment" value="Pay after order confirmation" defaultChecked/><CreditCard/><span><b>Pay after confirmation</b>Receive the final product and delivery total first.</span></label><label className="payment-option"><input type="radio" name="payment" value="Pay on collection or delivery if available"/><Truck/><span><b>Collection / delivery payment</b>Subject to confirmation by the store.</span></label></fieldset><label className="wide">Delivery notes<textarea name="notes" placeholder="Gate access, landmarks or product preferences"/></label><div className="checkout-summary wide"><span>{count} product{count===1?'':'s'} in this order</span><b>Final total confirmed before payment</b></div><button className="place-order wide" type="submit"><span>Place delivery order</span><Truck/></button></form></>}</motion.div></>}</AnimatePresence>

    <AnimatePresence>{lastAdded&&<motion.div className="quote-added-toast" role="status" aria-live="polite" initial={{opacity:0,y:20,scale:.97}} animate={{opacity:1,y:0,scale:1}} exit={{opacity:0,y:12,scale:.97}}><CircleCheck/><span><b>Added to cart</b>{lastAdded}</span><button onClick={()=>{setLastAdded(null);setCartOpen(true)}}>Review</button></motion.div>}</AnimatePresence>
    {count>0&&!cartOpen&&<motion.button className="floating-quote-button" onClick={()=>setCartOpen(true)} initial={{opacity:0,y:24}} animate={{opacity:1,y:0}} aria-label={`Review and validate quote with ${count} items`}><span><ShoppingBag/><i>View cart & checkout</i></span><b>{count} item{count===1?'':'s'}</b></motion.button>}
  </section>
}